### PR TITLE
Migrate flex adapter from drivers

### LINKED ISSUE #1: Migrate flex adapter from drivers
We're going to deprecate the drivers repo.

https://github.com/kubernetes-csi/drivers/tree/master/pkg/flexadapter

### PR DESCRIPTION
**Pull request by cofyc**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
/kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

- import release-tools (`git subtree add --prefix=release-tools https://github.com/kubernetes-csi/csi-release-tools.git master`)
- merge flexadapter related commits from drivers (failed because original commits does not pass cla check)
  - `git clone git@github.com:kubernetes-csi/drivers.git`
  - `git filter-branch --index-filter 'git rm --cached -qr --ignore-unmatch -- . && git reset -q $GIT_COMMIT -- app/flexadapter pkg/flexadapter' --prune-empty -- --all`
- ~~copy flexadapter files from drivers~~
- update docs and vendor dependencies

**Which issue(s) this PR fixes**:

Fixes #1

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by msau42** [comment]
@pohly could you help verify the release-tools import was done correctly?

**Comment by pohly** [comment]
> merge flexadapter related commits from drivers - failed because original commits does not pass cla check

We've had that before and it was agreed to by-pass the CLA check (https://github.com/kubernetes-csi/csi-driver-host-path/pull/1) - I personally prefer that over loosing history.

> could you help verify the release-tools import was done correctly?

Yes, all looks good and `make test` passes (which includes checking the `release-tools` directory).

**Comment by cofyc** [comment]
OK, I'll update it.

**Comment by cofyc** [comment]
I think it's better to keep the original commits too.
Reverted back to 30eddaa. PTAL.

**Comment by msau42** [comment]
/lgtm
/approve

Force merging to skip cla check

**Comment by msau42** [comment]
@cofyc can you also help setup test-infra for this repo?  Maybe just enable unit test jobs for now until we're ready for image building.

https://github.com/kubernetes/test-infra/tree/master/config/jobs/kubernetes-csi

**Pull request merged**
